<?php

namespace AppBundle\Repository;

/**
 * GameTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
